### ISSUE TITLE
Records with subrecords don't work

### ISSUE THREAD

**Issue by haljin** [haljin/rec_struct#1]
Given a header file:

```erlang
-record(test_record, { 
  a_field = 15,
  other_field}).  

-record(record_with_subrecord, {
  my_field = 13487,
  field_with_record = #test_record{}}).
```

The `defheader` macro now works but `defrecstruct` does not and complains about invalid quoted expressions. Probably needs a `Macro.escape/1` somewhere

**Comment by haljin** [comment]
Also sub records will not be converted to structs automatically

**Comment by gramosg** [comment]
Hello, I see this issue was already fixed in the repo's master branch, but it's not the current version in Hex. Is there any reason not to close this issue and push a new version to Hex?

Thanks!

**Comment by haljin** [comment]
The only reason is I kind of forgot about this library. :) I can push it a bit later.

**Comment by haljin** [comment]
Done, `0.3.0` is out
